let theme=[
    ['bg-theme1-background-main',
     'bg-theme1-background-keypad',
     'bg-theme1-background-screen',
    'bg-theme1-keys-btn1',
    'shadow-theme1-keys-btn1S',
    'bg-theme1-keys-btn2',
    'shadow-theme1-keys-btn2S',
    'bg-theme1-keys-btn3',
    'shadow-theme1-keys-btn3S',
    'text-theme1-text-white',
    'text-theme1-text-blue',
    'text-theme1-text-white',
 ],
 [  'bg-theme2-background-main',
    'bg-theme2-background-keypad',
    'bg-theme2-background-screen',
    'bg-theme2-keys-btn1',
    'shadow-theme2-keys-btn1S',
    'bg-theme2-keys-btn2',
    'shadow-theme2-keys-btn2S',
    'bg-theme2-keys-btn3',
    'shadow-theme2-keys-btn3S',
    'text-theme2-text-yellow',
    'text-theme2-text-yellow',
    'text-theme1-text-white',
 ],
 [  'bg-theme3-background-main',
    'bg-theme3-background-keypad',
    'bg-theme3-background-screen',
    'bg-theme3-keys-btn1',
    'shadow-theme3-keys-btn1S',
    'bg-theme3-keys-btn2',
    'shadow-theme3-keys-btn2S',
    'bg-theme3-keys-btn3',
    'shadow-theme3-keys-btn3S',
    'text-theme3-text-yellow',
    'text-theme3-text-yellow',
    'text-theme1-text-white',
 ]
]
   
export default theme;